import type { Project } from "@/types/database";

export const DEFAULT_PROJECTS: Project[] = [
  {
    id: "p1",
    slug: "dralo",
    name: "Dralo",
    description: "Web de inglés",
    type: "education",
    status: "in_progress",
    priority: 1,
    icon: "languages",
    color: "#3b82f6",
    created_at: new Date().toISOString(),
  },
  {
    id: "p2",
    slug: "open-to-work",
    name: "Open To Work",
    description: "ETT ya asentada",
    type: "recruitment",
    status: "established",
    priority: 2,
    icon: "briefcase",
    color: "#10b981",
    created_at: new Date().toISOString(),
  },
  {
    id: "p3",
    slug: "agarrame-las-pokebolas",
    name: "Agárrame las Pokebolas",
    description: "Empresa de impresión en 3D",
    type: "ecommerce",
    status: "active",
    priority: 3,
    icon: "printer",
    color: "#f59e0b",
    created_at: new Date().toISOString(),
  },
  {
    id: "p4",
    slug: "estoicoycalistenico",
    name: "Estoicoycalistenico",
    description: "Proyecto en pausa — retomar en el futuro",
    type: "wellness",
    status: "paused",
    priority: 4,
    icon: "heart",
    color: "#8b5cf6",
    created_at: new Date().toISOString(),
  },
  {
    id: "p5",
    slug: "cuento-que-fue",
    name: "Cuento Que Fue",
    description: "Canal de YouTube de historias y anécdotas",
    type: "youtube",
    status: "active",
    priority: 5,
    icon: "tv",
    color: "#ef4444",
    created_at: new Date().toISOString(),
  },
  {
    id: "p6",
    slug: "trabaja-la-mente",
    name: "Trabaja la Mente",
    description: "Canal de YouTube sobre mente, hábitos y productividad",
    type: "youtube",
    status: "active",
    priority: 6,
    icon: "brain",
    color: "#ec4899",
    created_at: new Date().toISOString(),
  },
  {
    id: "p7",
    slug: "tap-up",
    name: "Tap-up",
    description: "Patente que quiero desarrollar",
    type: "patent",
    status: "in_progress",
    priority: 7,
    icon: "lightbulb",
    color: "#06b6d4",
    created_at: new Date().toISOString(),
  },
  {
    id: "p8",
    slug: "tufitmentor360",
    name: "TuFitMentor360",
    description: "App de fitness y mentoría",
    type: "fitness",
    status: "active",
    priority: 8,
    icon: "dumbbell",
    color: "#84cc16",
    created_at: new Date().toISOString(),
  },
  {
    id: "p9",
    slug: "hype",
    name: "Hype",
    description: "Marca personal y contenido",
    type: "brand",
    status: "active",
    priority: 9,
    icon: "flame",
    color: "#f97316",
    created_at: new Date().toISOString(),
  },
];
